Removed excluded as it was causing error
TestEngine with ID 'junit-vintage' failed to discover tests java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: junit/runner/Version